# Generated by Django 5.2 on 2025-04-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_last_otp_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_sent_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
