# Generated by Django 5.2 on 2025-05-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chargingstation',
            index=models.Index(fields=['location'], name='stations_ch_locatio_36fc0d_idx'),
        ),
    ]
