# Generated by Django 5.2 on 2025-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='battery_capacity_kWh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
