# Generated by Django 5.2 on 2025-05-14 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_battery_capacity_kwh'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('battery_capacity_kWh', models.FloatField(blank=True, null=True)),
                ('range_per_charge_km', models.FloatField(blank=True, null=True)),
                ('charging_time', models.CharField(blank=True, max_length=50, null=True)),
                ('connector_type', models.CharField(blank=True, max_length=50, null=True)),
                ('charging_port_location', models.CharField(blank=True, max_length=50, null=True)),
                ('fast_charging_support', models.BooleanField(default=False)),
                ('dc_charging_compatibility', models.BooleanField(default=False)),
                ('price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('launch_year', models.IntegerField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='battery_capacity_kWh',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vehicles', to='vehicles.vehiclecatalog'),
        ),
    ]
