# Generated by Django 5.2 on 2025-05-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehiclecatalog_remove_vehicle_battery_capacity_kwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecatalog',
            name='vehicle_type',
            field=models.CharField(max_length=100),
        ),
    ]
