# Generated by Django 5.2 on 2025-05-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehiclecatalog_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecatalog',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecatalog',
            name='charging_port_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecatalog',
            name='charging_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecatalog',
            name='connector_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
