# Generated by Django 5.2 on 2025-05-15 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehiclecatalog_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecatalog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclecatalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
