# Generated by Django 5.2 on 2025-05-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehiclecatalog_created_at_vehiclecatalog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='custom_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='custom_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
